version: '3.8'

services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: auth_microservices_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - microservices-net

  auth-service:
    build: ./auth-service
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_microservices_db
    volumes:
      - ./common:/app/common
    networks:
      - microservices-net

  forgot-password-service:
    build: ./forgot-password-service
    ports:
      - "8001:8001"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_microservices_db
    volumes:
      - ./common:/app/common
    networks:
      - microservices-net

  update-password-service:
    build: ./update-password-service
    ports:
      - "8002:8002"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/auth_microservices_db
    volumes:
      - ./common:/app/common
    networks:
      - microservices-net

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - auth-service
      - forgot-password-service
      - update-password-service
    networks:
      - microservices-net

volumes:
  postgres_data:

networks:
  microservices-net:
    driver: bridge 